name: pusher
description: Pusher HTTP Dart Library
author: Adao Junior <itsjunnior@gmail.com>
homepage: https://github.com/adaojunior/pusher
version: 1.0.1-beta
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  crypto: "^2.0.6"
  http: "^0.12.0+1"
dev_dependencies:
  test: '^1.5.3'
