name: pusher
description: Pusher HTTP Dart Library
author: Adao Junior <dev@pardim.com>
homepage: https://github.com/adaojunior/pusher
version: 2.0.0-alpha+1
environment:
  sdk: ">=2.6.1 <3.0.0"
dependencies:
  crypto: "^2.1.3"
  http: "^0.12.0+2"
dev_dependencies:
  test: '^1.9.4'
